[package]
name = "minus-i"
version = "0.1.0"
authors = ["Dimitri Polonski <d.polonski@wmt.team>"]
edition = "2018"

[dependencies]
minus-i-derive = {path = "minus-i-derive" }

[features]
default = ["std"]
std = []

[[example]]
name = "minimal"
path = "examples/minimal.rs"

[[example]]
name = "tab_completion"
path = "examples/tab_completion.rs"

[dev_dependencies]
rustyline = "6"
rustyline-derive = "0.3"
