[package]
name = "repl"
version = "0.1.0"
authors = ["Dimitri Polonski <d.polonski@wmt.team>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
repl_derive = {path = "repl_derive"}

[dev-dependencies]
trybuild = "1"

[features]
default = ["std"]
std = []
